# USER BUNDLE
banana_user:
    resource: "@BananaUserBundle/Resources/config/routing.yml"

# SECURITY
homepage:
    path:      /
    defaults:  { _controller: BananaUserBundle:Default:index}

#app_blog:
    #resource: "@AppBundle/Resources/config/routing.yml"

# SONATA ADMIN BUNDLE
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix:   /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix:   /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix:   /admin

#sonata_user_impersonating:
   # pattern:  /
   # defaults: { _controller: SonataPageBundle:Page:catchAll }
